# Generated by Django 4.0.6 on 2022-07-16 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardSeries', models.CharField(max_length=2)),
                ('cardId', models.CharField(max_length=16, unique=True)),
                ('startDate', models.DateTimeField(verbose_name='Published date')),
                ('endDate', models.DateTimeField(verbose_name='Expired date')),
                ('cvv', models.CharField(max_length=3)),
                ('count', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Blocked'), (2, 'Expired')])),
            ],
        ),
        migrations.CreateModel(
            name='CardOperationLogString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationType', models.IntegerField(choices=[(0, 'Card Created'), (1, 'Card Status Changed'), (2, 'Card Deleted')], editable=False)),
                ('cardSeries', models.CharField(editable=False, max_length=2)),
                ('cardId', models.CharField(editable=False, max_length=16)),
                ('cardCount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneyAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('operationType', models.IntegerField(choices=[(0, 'Income'), (1, 'Outcome')])),
                ('purpouce', models.CharField(max_length=255)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardDb.card')),
            ],
        ),
    ]
